{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "q2a.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "q2a.name" . }}
    helm.sh/chart: {{ include "q2a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
  {{- with .Values.ingress.annotations -}}
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.host }}
      secretName: {{ include "q2a.fullname" . }}-tls-certs
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "q2a.nginx-service-name" . }}
              servicePort: {{ .Values.nginx.service.port }}

---
{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "q2a.fullname" . }}-tls-certs
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}

{{- end }}
