apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "q2a.fullname" . }}-q2a
  labels:
    app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a
    helm.sh/chart: {{ include "q2a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-q2a
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: q2a
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.q2a.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a
      app.kubernetes.io/instance: {{ .Release.Name }}-q2a
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a
        app.kubernetes.io/instance: {{ .Release.Name }}-q2a
    spec:
      containers:
        - name: {{ .Chart.Name }}-q2a
          image: "{{ .Values.q2a.image.address }}"
          imagePullPolicy: {{ .Values.q2a.image.pullPolicy }}
          volumeMounts:
            {{- include "q2a.shared-volume-mounts" . | nindent 12 }}
            - name: q2a-init
              mountPath: /docker-entrypoint-init.d
          ports:
            - name: php-fpm
              containerPort: {{ .Values.q2a.php_fpm_port }}
              protocol: TCP
          env:
            - name: QA_DB_HOSTNAME
              value: {{ include "q2a.mysql-service-name" . }}
            - name: QA_DB_USER
              value: {{ .Values.mysql.auth.user }}
            - name: QA_DB_PASS
              value: {{ .Values.mysql.auth.user_password }}
            - name: QA_DB_NAME
              value: {{ .Values.mysql.database_name }}
            {{ if .Values.q2a.env -}}
            {{- toYaml .Values.q2a.env | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        {{- include "q2a.q2a-shared-volumes" . | nindent 8 }}
        - name: q2a-init
          configMap:
            name: {{ include "q2a.fullname" . }}-q2a-init
            defaultMode: 0755
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace}}
  name: {{ include "q2a.q2a-service-name" . }}
  labels:
    app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a
    helm.sh/chart: {{ include "q2a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-q2a
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: q2a
    app.kubernetes.io/component: server
spec:
  ports:
    - name: php-fpm
      port: {{ .Values.q2a.service.port }}
      targetPort: php-fpm
  selector:
    app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a
    app.kubernetes.io/instance: {{ .Release.Name }}-q2a

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace}}
  name: {{ include "q2a.fullname" . }}-q2a-init
data:
  {{- ($.Files.Glob "provisioning/q2a/*").AsConfig | nindent 2 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "q2a.fullname" . }}-q2a-data
  labels:
    app.kubernetes.io/name: {{ include "q2a.name" . }}-q2a-data
    helm.sh/chart: {{ include "q2a.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-q2a-data
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: q2a
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.q2a.volume.size }}
  {{- if .Values.q2a.volume.storage_class }}
  storageClassName: {{ .Values.q2a.volume.storage_class }}
  {{- end }}
